services:
  - type: web
    name: django-ecommerce
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your-django-secret-key
