# Generated by Django 5.2.5 on 2025-08-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('boys_fashion', 'Boys Fashion'), ('girls_fashion', 'Girls Fashion'), ('soap', 'Soap'), ('stroller', 'Stroller'), ('bottle', 'Bottle'), ('offers', 'Offers'), ('pampers', 'Pampers')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
